name: cdk deploy

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
jobs:
  firebase_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Hello world
        run: echo Hello world $FIRST_NAME $middle_name
        env:
          FIRST_NAME: Mona
          middle_name: The

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Setup dependencies
        run: npm install

      - name: Setup env file
        run: echo $authDomain $projectId && bash ./ops/set-env.sh $apiKey $authDomain $databaseURL $projectId $storageBucket $messagingSenderId $appId $measurementId
        env:
          apiKey: ${{ secrets.API_KEY }}
          authDomain: stg-grapevin-tech.firebaseapp.com
          databaseURL: https://stg-grapevin-tech.firebaseio.com
          projectId: stg-grapevin-tech
          storageBucket: stg-grapevin-tech.appspot.com
          messagingSenderId: 351226426855
          appId: ${{ secrets.APP_ID }}
          measurementId: G-4CWQGZFN3T

      - name: Initial Public Folder
        run: |
          [ ! -d "./public" ]
          mkdir ./public

      - name: Clean Code & Build
        run: |
          npm run build:firebase

      - name: Deploy Code
        run: |
          firebase deploy --only functions,hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}



