name: cdk deploy

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
jobs:
  grapevin_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup env file
        run: bash ./ops/set-env.sh $apiKey $authDomain $databaseURL $projectId $storageBucket $messagingSenderId $appId $measurementId
        env:
          apiKey: ${{ secrets.API_KEY }}
          authDomain: stg-grapevin-tech.firebaseapp.com
          databaseURL: https://stg-grapevin-tech.firebaseio.com
          projectId: ${{ secrets.PROJECT_ID }}
          storageBucket: stg-grapevin-tech.appspot.com
          messagingSenderId: 351226426855
          appId: ${{ secrets.APP_ID }}
          measurementId: G-4CWQGZFN3T

      - name: remove old code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/app/gravin-tech
            rm -rf ~/app/gravin-tech/*
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./"
          target: "~/app/gravin-tech"

      - name: ssh script to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/app/gravin-tech
            bash ./ops/run-server.sh
