name: cdk deploy

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
jobs:
  firebase_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Setup dependencies
        run: npm install

      - name: Setup env file
        run: bash ./ops/set-env.sh $apiKey $authDomain $databaseURL $projectId $storageBucket $messagingSenderId $appId $measurementId
        env:
          apiKey: ${{ secrets.API_KEY }}
          authDomain: ${{ secrets.AUTH_DOMAIN }}
          databaseURL: ${{ secrets.DATABASE_URL }}
          projectId: ${{ secrets.PROJECT_ID }}
          storageBucket: ${{ secrets.STORAGE_BUCKET }}
          messagingSenderId: ${{ secrets.MESSAGING_SENDER_ID }}
          appId: ${{ secrets.APP_ID }}
          measurementId: ${{ secrets.MEASUREMENT_ID }}

      - name: Clean Code & Build
        run: |
          npm run clean && npm run build

      - name: Build Layer Packages
        run: |
          cd functions && npm install && cd ..

      - name: Deploy Code
        run: |
          firebase deploy --only functions,hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}



